services:
  postgres:
    image: postgres
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testpassword
      MINIO_SERVER_URL: "http://minio:9000"
      MINIO_CONSOLE_PORT: "9001"
    command: server /data --console-address ":9001"

volumes:
    minio_data: